### PR TITLE
Marker functionality patch

### LINKED ISSUE #220: HUD marker does not display correctly for players in a classroom
**Describe the bug**
When a player records a coordinate in a classroom and then clicks the place a marker button, the HUD marker appears only for the player who placed the marker.

**To Reproduce**
1. Open student notebook.
2. Navigate to Map tab.
3. Type a message and click Save Current Coordinates.
4. Highlight the new message in the list and then click the place marker in world button.
5. Observe that other players cannot see the HUD marker that is being shared.

**Expected behavior**
All other players in the classroom should be able to see the HUD marker. Need to take care that `minetest.register_on_joinplayer` and `minetest.register_on_leaveplayer` are set up to manage these HUD markers for players that are coming and going as well as when players teleport between classrooms. 

**Desktop (please complete the following information):**
 - Version 5.7.0

### PR DESCRIPTION
**Pull request by Lowie375**
Makes markers work as originally intended, (hopefully) fixing #220

### CODE REVIEW

File: mods/mc_core/coordinates.lua [hunk 1]
```diff
@@ -1,74 +1,106 @@
 function mc_core.record_coordinates(player, message)
-	if mc_core.checkPrivs(player, {interact = true}) then
-		local pmeta = player:get_meta()
-		local pos = player:get_pos()
-		local realmID = pmeta:get_int("realm")
-		local temp, clean_message
-		clean_message = minetest.formspec_escape(message)
-		temp = minetest.deserialize(pmeta:get_string("coordinates")) or {realms = {}, coords = {}, note_map = {}}
+    if mc_core.checkPrivs(player, {interact = true}) then
```
Comment (pauldpickell) [inline mods/mc_core/coordinates.lua:2]: This should be checking for `shout = true`, too.

**Review by pauldpickell — CHANGES_REQUESTED** [review]

File: mods/mc_core/coordinates.lua (hunk 1 above)
Comment (Lowie375) [reply mods/mc_core/coordinates.lua:2]: Right, thanks for catching that!

Comment (Lowie375) [reply mods/mc_core/coordinates.lua:2]: I've added the priv check to the callbacks for the "mark" and "share" buttons rather than the coordinate recording function (this one).
People without `shout` should still be able to record coordinates if they'd like, but they should not be able to share the notes associated with them.

**Comment by Lowie375** [comment]
Apologies for all the whitespace changes introduced - they're mainly to clean up file formatting. There's a viewing toggle for them in the "Files changed" tab, under the settings icon.

**Review by pauldpickell — APPROVED** [review]
